services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: safe_monitor
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  test-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: safe_monitor_test
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    command: redis-server --requirepass samplepassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379:0:samplepassword
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
