apiVersion: batch/v1
kind: Job
metadata:
  name: circuits-job
spec:
  ttlSecondsAfterFinished: 300  # Delete automatically 5 minutes after completion
  template:
    spec:
      containers:
        - name: circuits-runner
          image: wshino/circuits-runner:test5
          imagePullPolicy: Always  # Always pull the latest image
          env:
            - name: REPO_URL
              value: "${REPO_URL}"
            - name: COMMIT_HASH
              value: "${COMMIT_HASH}"
          resources:
            requests:
              cpu: "8"
              memory: "16Gi"
            limits:
              cpu: "16"
              memory: "100Gi"
      restartPolicy: Never