apiVersion: batch/v1
kind: Job
metadata:
  name: circuits-job
spec:
  ttlSecondsAfterFinished: 60  # Delete automatically 1 minute after completion
  template:
    spec:
      nodeSelector:
        cloud.google.com/machine-family: c3
      containers:
        - name: circuits-runner
          image: wshino/circuits-runner:test5
          imagePullPolicy: Always  # Always pull the latest image
          env:
            - name: REPO_URL
              value: "${REPO_URL}"
            - name: COMMIT_HASH
              value: "${COMMIT_HASH}"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]  # Add a delay before container termination to allow log collection
          resources:
            requests:
              cpu: "8"
              memory: "16Gi"
            limits:
              cpu: "16"
              memory: "64Gi"
      restartPolicy: Never
      terminationGracePeriodSeconds: 30  # Ensure adequate time for graceful shutdown