apiVersion: batch/v1
kind: Job
metadata:
  name: circuits-job
spec:
  ttlSecondsAfterFinished: 300  # Delete automatically 5 minutes after completion
  template:
    spec:
      containers:
        - name: circuits-runner
          image: wshino/circuits-runner@sha256:3a089cde127bc40fd2244c555e01d51fe4a7abfa4bd636108723c8dfa8ae7a45
          env:
            - name: REPO_URL
              value: "${REPO_URL}"
            - name: COMMIT_HASH
              value: "${COMMIT_HASH}"
          resources:
            requests:
              cpu: "8"
              memory: "16Gi"
            limits:
              cpu: "16"
              memory: "32Gi"          
      restartPolicy: Never