[package]
name = "relayer"
version = "1.1.0"
edition = "2021"

[dependencies]
tower-http = { version = "0.4", git = "https://github.com/tower-rs/tower-http.git", features = [
    "cors",
], rev = "f33c3e038dc85b8d064541e915d501f9c9e6a6b4" }
tokio = { version = "1.0", features = ["full"] }
sled = "0.34.2"
anyhow = "1.0.75"
dotenv = "0.15.0"
oauth2 = "4.3.0"
async-imap = { version = "0.9.1", default-features = false, features = [
    "runtime-tokio",
] }
async-native-tls = { version = "0.5.0", default-features = false, features = [
    "runtime-tokio",
] }
serde = { version = "1.0", features = ["derive"] }
webbrowser = "0.8.11"
serde_json = "1.0.68"
tiny_http = "0.12.0"
lettre = { version = "0.10.4", features = ["tokio1", "tokio1-native-tls"] }
ethers = { version = "2.0.10", features = ["abigen"] }
relayer-utils = { version = "0.4.2", git = "https://github.com/zkemail/relayer-utils.git" }
futures = "0.3.28"
sqlx = { version = "=0.7.3", features = ["postgres", "runtime-tokio"] }
regex = "1.10.2"
axum = "0.6.20"
rand = "0.8.5"
reqwest = "0.11.22"
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2.16"
hex = "0.4.3"
chrono = "0.4.38"
ff = { version = "0.13.0", default-features = false, features = ["std"] }
async-trait = "0.1.36"
handlebars = "4.4.0"
graphql_client = { version = "0.13.0", features = ["reqwest"] }
lazy_static = "1.4"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_warn",
] }
slog-async = "2.8.0"
slog-term = "2.9.0"
slog-json = "2.6.1"
file-rotate = "0.7.5"
base64 = "0.21.7"
uuid = "1.8.0"
http = "1.1.0"
ic-agent = { version = "0.37.1", features = ["pem", "reqwest"] }
ic-utils = "0.37.0"
candid = "0.10.10"
thiserror = "1.0.63"
rustc-hex = "2.1.0"

[build-dependencies]
ethers = "2.0.10"
