name: Build-Test-Fmt

on:
  [push]

jobs:
  build-test-fmt:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - run: rustup show

    - uses: Swatinem/rust-cache@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "yarn"

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@v1
      with:
        version: nightly-cafc2606a2187a42b236df4aa65f4e8cdfcea970

    - name: Run tests
      working-directory: packages/contracts
      run: forge build
    
    - name: Build
      run: cargo build
      
    - name: Test
      run: cargo test
