name: Clippy Lint Check

on: [pull_request]

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy -- -D warnings
