name: Unit Tests

on: [push]

jobs:
  circuits:
    name: circuits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Download circom v2.1.9 (Linux)
        run: wget https://github.com/iden3/circom/releases/download/v2.1.9/circom-linux-amd64 -O /usr/local/bin/circom && chmod +x /usr/local/bin/circom

      - name: Print circom version
        run: circom --version

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run tests
        working-directory: packages/circuits
        run: yarn test --runInBand --no-cache

  contracts:
    name: contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          version: nightly-0079a1146b79a4aeda58b0258215bedb1f92700b

      - name: Run tests
        working-directory: packages/contracts
        run: yarn test

      - name: Run script tests
        working-directory: packages/contracts
        run: yarn test:script

  relayer:
    name: relayer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1.2.0
        with:
          version: nightly-0079a1146b79a4aeda58b0258215bedb1f92700b

      - name: Build contracts
        working-directory: packages/contracts
        run: yarn build

      - name: Run tests
        working-directory: packages/relayer
        run: cargo test
